apiVersion: v2
name: interpolator-operator
description: A Helm chart to distribute interpolator-operator
type: application
version: 0.11.0
appVersion: "0.11.0"
keywords:
  - kubernetes
  - operator
annotations:
  kubebuilder.io/generated-by: kubebuilder
