controllerManager:
  manager:
    args:
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: registry.gitlab.ggniadekit.com/devops/container-images/controller
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    imagePullSecrets:
    - name: gitlab-registry
  replicas: 1
  serviceAccount:
    annotations: {}

kubernetesClusterDomain: cluster.local
