---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - interpolator.io
  resources:
  - interpolators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - interpolator.io
  resources:
  - interpolators/finalizers
  verbs:
  - update
- apiGroups:
  - interpolator.io
  resources:
  - interpolators/status
  verbs:
  - get
  - patch
  - update
