---
apiVersion: v1
kind: Secret
metadata:
  name:  testing-secret
  namespace: default
data:
   password:  cGFzc3dvcmQ=
type: Opaque
---
apiVersion: v1
data:
  username: admin
kind: ConfigMap
metadata:
  name: testing-cm
  namespace: default
