---
apiVersion: interpolator.io/v1
kind: Interpolator
metadata:
  name: interpolator-sample
  namespace: default
spec:
  inputSecret:
  - name: testing-cm
    type: ConfigMap
    namespace: default
    key: username
  - name: testing-secret
    type: Secret
    namespace: default
    key: password
  outputSecret:
    - sourcekey: username
      outputkey: username-rooted
      value: "{{ username }}-with-permissions"
    - sourcekey: password
      outputkey: password-changed
      value: "{{ password }}-with-something-added"
  outputSecretName: testing-output
---
apiVersion: v1
kind: Secret
metadata:
  name:  testing-secret
  namespace: default
data:
   password:  cGFzc3dvcmQ=
type: Opaque
---
apiVersion: v1
data:
  username: admin
kind: ConfigMap
metadata:
  name: testing-cm
  namespace: default