---
apiVersion: v1
kind: Secret
metadata:
  name:  testing-secret
  namespace: default
data:
   password:  cGFzc3dvcmQ=
type: Opaque
---
apiVersion: v1
data:
  username: admin
kind: ConfigMap
metadata:
  name: testing-cm
  namespace: default
---
apiVersion: interpolator.io/v1
kind: Interpolator
metadata:
  name: interpolator-sample
  namespace: default
spec:
  inputSecrets:
  - name: testing-cm
    kind: ConfigMap
    namespace: default
    key: username
  - name: testing-secret
    kind: Secret
    namespace: default
    key: password
  outputSecrets:
    - sourcekey: username
      outputkey: username-rooted
      value: "{{ username }}-with-permissions"
    - sourcekey: password
      outputkey: password-changed
      value: "{{ password }}-with-something-added"
  outputName: testing-output
  outputKind: ConfigMap
---
apiVersion: interpolator.io/v1
kind: Interpolator
metadata:
  name: interpolator-sample2
  namespace: default
spec:
  inputSecrets:
  - name: testing-cm
    kind: ConfigMap
    namespace: default
    key: username
  - name: testing-secret
    kind: Secret
    namespace: default
    key: password
  outputSecrets:
    - sourcekey: username
      outputkey: username-rooted
      value: "{{ username }}-with-permissions"
    - sourcekey: password
      outputkey: password-changed
      value: "{{ password }}-with-something-added"
  outputName: testing-output
  outputKind: Secret