apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "interpolator.fullname" . }}-viewer-role
  labels:
  {{- include "interpolator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - interpolator.interpolator.io
  resources:
  - interpolators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - interpolator.interpolator.io
  resources:
  - interpolators/status
  verbs:
  - get