apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "interpolator.fullname" . }}-interpolator-editor-role
  labels:
  {{- include "interpolator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - interpolator.interpolator.io
  resources:
  - interpolators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - interpolator.interpolator.io
  resources:
  - interpolators/status
  verbs:
  - get