apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "interpolator.fullname" . }}-manager-role
  labels:
  {{- include "interpolator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - interpolator.io
  resources:
  - interpolators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - interpolator.io
  resources:
  - interpolators/finalizers
  verbs:
  - update
- apiGroups:
  - interpolator.io
  resources:
  - interpolators/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "interpolator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "interpolator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "interpolator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: {{ include "interpolator.fullname" . }}-controller-manager
  namespace: '{{ .Release.Namespace }}'