{{- if .Values.prometheusMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "interpolator.fullname" . }}-metrics-monitor
  labels:
  {{- include "interpolator.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.prometheusCRDS.enabled }}
    "helm.sh/hook": post-install
  {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.prometheusMonitor.interval }}
    port: metrics
  selector:
    matchLabels:
      control-plane: controller-manager
{{- end -}}