{{- if .Values.prometheusMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "interpolator.fullname" . }}-metrics-monitor
  labels:
    control-plane: controller-manager
  {{- include "interpolator.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      control-plane: controller-manager
{{- end -}}