{{- if .Values.metricsService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "interpolator.fullname" . }}-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "interpolator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "interpolator.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}
{{- end -}}