name: Release Container

on:
  push:
    paths-ignore:
    - 'charts/**'
    branches:
      - master
      - dev

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"
  PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read VERSION file
        id: read_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.PLATFORMS }}
          context: .
          file: Dockerfile
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
